# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on: workflow_dispatch

permissions:
  contents: write

jobs:
  prepare_extension:
    name: Prepare Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - run: tree
      - uses: jacobtomlinson/gha-find-replace@3.0.5
        id: far
        with:
          include: "*/extension/*"
          find: "{{baseURL}}"
          replace: secrets.baseUrl
      - run: echo ${{ steps.far.outputs.modifiedFiles }}
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./static/extension.zip ./src/lib/extension
      - run: tree

  
