# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on: workflow_dispatch

permissions:
  contents: write

jobs:
  prepare_extension:
    name: Prepare Extension
    runs-on: ubuntu-latest
    steps:
      - uses: jacobtomlinson/gha-find-replace@3.0.5
        with:
          include: "*/extension/*"
          find: "{{baseURL}}"
          replace: secrets.baseUrl

  zip_extension:
    needs: prepare_extension
    name: Zip Extension
    runs-on: ubuntu-latest
    steps:
      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "node_modules|dist|.git|.husky"
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./static/extension.zip ./src/lib/extension
      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          exclude: "node_modules|dist|.git|.husky"

  
