# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on: workflow_dispatch

jobs:
  deploy:
      name: Deploy app
      runs-on: ubuntu-latest
      concurrency: deploy-group # optional: ensure only one action runs at a time
      steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0
        - name: Replace baseURL placeholder
          run: find ./src/lib/extension/ -name "*.js" -type f -exec sed -i 's/{{baseURL}}/${{ secrets.baseUrl }}/g' {} \;
        - uses: vimtor/action-zip@v1.2
          with:
            files: ./src/lib/extension
            dest: ./static/extension.zip
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
