# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Deploy
on: workflow_dispatch

permissions:
  contents: write

jobs:
  prepare_extension:
    name: Prepare Extension
    runs-on: ubuntu-latest
    steps:
      - run: tree
      - uses: jacobtomlinson/gha-find-replace@3.0.5
        with:
          include: "*/extension/*"
          find: "{{baseURL}}"
          replace: secrets.baseUrl
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r ./static/extension.zip ./src/lib/extension

  deploy:
      needs: prepare_extension
      name: Deploy app
      runs-on: ubuntu-latest
      concurrency: deploy-group # optional: ensure only one action runs at a time
      steps:
        - uses: actions/checkout@v4
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - run: flyctl deploy --remote-only
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
